# Generated by Django 2.2.16 on 2022-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221021_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='Описание группы', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Описание группы', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
